layers/meta-balena-isg-503:remove the migrate and recovery modules
balena-os/balena-isg pull request #246
Opened 2023-04-14 01:36 UTC by RockSupport

The initramfs image that exceeds the allocated space. remove some new modules

Changelog-entry:layers/meta-balena-isg-503:remove the migrate and recovery modules

2023-04-14 01:52 UTC, RockSupport commented
@resin-jenkins ok to test

2023-04-14 01:52 UTC, RockSupport commented
@resin-jenkins test this please

2023-04-14 03:39 UTC, RockSupport commented
lgtm

2023-04-14 03:40 UTC, RockSupport commented
I  am not administrator _~_

2023-04-14 09:50 UTC, RockSupport commented
hi @alexgg Could you help merge this Pr?

2023-04-14 09:52 UTC, RockSupport commented
lgtm

2023-04-14 14:37 UTC, alexgg commented on layers/meta-balena-isg-503/recipes-kernel/linux/files/Dockerfile
@RockSupport would you mind adding a note to the commit to state that this is needed because of https://github.com/JeffyCN/meta-rockchip/commit/1258d9241edf512b0d10076896fd5ce36ba58cb4?

2023-04-14 14:38 UTC, alexgg requested changes
I left a note to add some context to a commit that explains why extending the Dockerfile is needed.

2023-04-14 14:38 UTC, alexgg commented
@resin-jenkins ok to test

2023-04-14 14:38 UTC, alexgg commented
@resin-jenkins test this please

2023-04-17 02:04 UTC, RockSupport commented on layers/meta-balena-isg-503/recipes-kernel/linux/files/Dockerfile
Thanks for your commented, As jeffyCN's note,this is  for " Support python3 for dunfell", Now I have updated this project to kirkstone,But it need this too.
the recipes-kernel  in https://github.com/JeffyCN/meta-rockchip is too old，missing some features of px30,I use this recipes-kernel https://github.com/balena-os/balena-isg/tree/master/layers/meta-balena-isg-503/recipes-kernel/linux,which is 5.10.110.

2023-04-17 09:20 UTC, alexgg commented
@resin-jenkins retest this please

2023-04-17 10:18 UTC, alexgg approved these changes
lgtm

2023-04-17 10:18 UTC, merged

2023-04-19 10:17 UTC, acostach commented
@RockSupport how can u-boot & kernel logs be obtained, which UART pins should be used? I believe the RS232 debug pins should be GND, B2/RX1, A2,TX1 at baudrate 1500000 8N1 but I don't see any logs. Thanks

2023-04-19 10:27 UTC, RockSupport commented
Hi @alexgg ， uboot is same as before,，kernel logs can obtained by dmesg. 
and we use uart2_m1 in the board
![image](https://user-images.githubusercontent.com/88175479/233046803-cd751dd8-176c-47c3-8c61-95ec2fd4491a.png)

2023-04-20 01:55 UTC, RockSupport commented
hi @acostach  only on the 40 pin header
And sorry for unreasonable design
**please make sure compile with '-d'**
 ./balena-yocto-scripts/build/barys -m isg-503 --shared-downloads /home/rockemb/Balena/downloads -d

**use ttl port** 
![0c921bd2834675ac752d5c3e15e3ff3](https://user-images.githubusercontent.com/88175479/233237525-ff978e25-84c4-4cbc-ba11-8554d36fbe8a.jpg)

![image](https://user-images.githubusercontent.com/88175479/233237907-0d68ef31-3aa2-4f54-afa9-c39da4b99c38.png)

2023-04-20 14:28 UTC, acostach commented
Thank you @RockSupport , I was able to login with the latest git master and a deveopment build, on the 40pin header. Older revisions didn't receive chars in Linux, only in u-boot, but the latest HEAD revision works fine for both.

2023-04-21 10:15 UTC, RockSupport commented
@acostach maybe miss some config in the dts.
I just debug uboot by uart. did not use after boot
use balena ssh instead

2023-04-24 14:35 UTC, acostach commented
@RockSupport one more question, it looks like a random MAC address is generated for the ethernet on each device boot, which leads to the device always getting a different IP although the dhcp lease isn't expired. Is this expected behavior? We're seeing this with both devices we have using the latest git master revision.

```
[    1.004254] rk_gmac-dwmac ff360000.ethernet: rk_get_eth_addr: rk_vendor_read eth mac address failed (-1)
[    1.006023] rk_gmac-dwmac ff360000.ethernet: rk_get_eth_addr: generate random eth mac address: fa:23:26:f9:6e:7c
[    1.007912] rk_gmac-dwmac ff360000.ethernet: rk_get_eth_addr: rk_vendor_write eth mac address failed (-1)
[    1.009697] rk_gmac-dwmac ff360000.ethernet: rk_get_eth_addr: id: 0 rk_vendor_read eth mac address failed (-1)
[    1.011547] rk_gmac-dwmac ff360000.ethernet: rk_get_eth_addr: mac address: fa:23:26:f9:6e:7c
[    1.013118] rk_gmac-dwmac ff360000.ethernet: device MAC address fa:23:26:f9:6e:7c
```
reboot
```
[    1.005613] rk_gmac-dwmac ff360000.ethernet: rk_get_eth_addr: rk_vendor_read eth mac address failed (-1)
[    1.007389] rk_gmac-dwmac ff360000.ethernet: rk_get_eth_addr: generate random eth mac address: 82:64:48:63:71:53
[    1.009275] rk_gmac-dwmac ff360000.ethernet: rk_get_eth_addr: rk_vendor_write eth mac address failed (-1)
[    1.011048] rk_gmac-dwmac ff360000.ethernet: rk_get_eth_addr: id: 0 rk_vendor_read eth mac address failed (-1)
[    1.012907] rk_gmac-dwmac ff360000.ethernet: rk_get_eth_addr: mac address: 82:64:48:63:71:53
[    1.014475] rk_gmac-dwmac ff360000.ethernet: device MAC address 82:64:48:63:71:53
```

2023-04-25 05:45 UTC, RockSupport commented
hi @acostach ，we have write our mac to the devices in factory.So "rk_vendor_read eth mac address" will sucess. 
Beside we need keep UUID keep the same  after update from Dunfell to Kirkstone

2023-04-25 06:57 UTC, acostach commented
@RockSupport for the devices we have on our side the "rk_vendor_read eth mac address" always fails, I assume the MAC has not been written in the factory for our units. Can we write it from Linux on our devices so that it stops failing our tests, do you have a line that we can use? Thanks

2023-04-25 07:18 UTC, RockSupport commented
@acostach we just have an windows tools to write mac.I am not familiar with this tools 
![image](https://user-images.githubusercontent.com/88175479/234201355-72f0798a-b1aa-4fcf-b571-07dae458d2f5.png)
I  try to use this tool with balenaOS and write a document for you.

2023-04-25 07:58 UTC, RockSupport commented
hi @acostach  How can I send the RKDevInfoWriteTool to you?
I  have tested in balenaOS and here is the step how to enter loader
balena ssh deviceIP
reboot loader
press the green button
![image](https://user-images.githubusercontent.com/88175479/234210168-ca30d427-bfbc-4487-84a0-664c9fc29d77.png)
![image](https://user-images.githubusercontent.com/88175479/234210843-a10400be-9ae0-4029-8e3a-326dc2cabb25.png)

2023-04-25 08:54 UTC, acostach commented
@RockSupport is the rkdevinfowritetool here https://en.t-firefly.com/doc/download/67.html good?

Also, which port should I connect to the Windows PC, the USB-C port? Are there some pins that I have to jumper for rkdevinfowritetool to talk to the board?

2023-04-25 08:58 UTC, RockSupport commented
@acostach I think the rkdevinfowritetool here https://en.t-firefly.com/doc/download/67.html is good
with "reboot loader" in ssh or console will enter loader mode

2023-04-25 12:14 UTC, acostach commented
Thank you @RockSupport , rkdevinfowritetool worked for flashing the eeprom with the MAC number. Could you please tell me again the TX, RX and GND pin numbers for the UART? I see you deleted the schematic and I didn't get to save the pin numbers. Thanks

2023-04-25 12:37 UTC, RockSupport commented
@acostach Sorry I thought the github will send a mail to you 
![image](https://user-images.githubusercontent.com/88175479/234278076-ecc25ab9-9a06-43e7-8d26-40f9954edf3f.png)

2023-04-25 12:44 UTC, RockSupport commented
@acostach there is not eeprom store mac addr, the rkdevinfowritetool will write mac info to emmc, But I am not know the detail about that.maybe rk_vendor_read/write can give something useful